---
title: "ESM 204 - Assignment 3"
author: "Jamie Miller"
date: "May 18, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(stargazer) # To make nicely formatted table of regression analysis
```

```{r, include = FALSE}
# Read in data
whales <- read_csv("HW3Data.csv")
```


1. Create a linear probability model that predicts a respondent’s probability of voting ‘yes’ on the ballot based on their age, income, NEP score, the risk reduction offered by the program, and the cost of the program to that respondent. Show the model and interpret the regression coefficients.
```{r}
# Regression - linear probability model
vote_lm <- lm(vote ~ risk + bid + NEP + income + age, data = whales)
vote_lm

# vote = 0.1196977 + 0.0007445(risk) - 0.0010699(bid) + 0.0158639(NEP) + 0.0088282(incomeone_percent) + 0.0027386(incomepoor) + 0.0074891(incomerich) + 0.0467922(incomevery_rich) + 0.0099816(agetofifty) - 0.0201190(agetoforty) - 0.0162261(agetosixty) + 0.0204401(agetothirty)

# (1) “risk”: level of risk reduction, (2) “bid”: annual payment for the household, (3) “vote”: 1 is yes, 0 is no, (4)”NEP” : measure of environmental concern (5)”income”: categorical variable for income level, (6)”age”: categorical variable for age.

summary(vote_lm) # Not sure this is needed, but here it is.


# write formal model equation with table of results.
# - risk, coefficient estimate, SE, p-value, or ***
# round in display


coeff <- vote_lm$coefficients
coeff

vote_lm$coefficients["risk"]

```


```{r, results ='asis'}
# stargazer for the results
table_vote_lm<- stargazer(vote_lm)


### Make a nice table
```


